# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: generate_family_file.py 9734 2011-11-09 22:17:11Z valhallasw $
Configuration parameters:
  url = http://sots2.rorschach.net/SotS2_Codex
  name = sots2

Please do not commit this to the SVN repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'sots2'
        self.langs = {
            'en': u'sots2.rorschach.net',
        }

        self.namespaces[-2] = self.namespaces.get(-2, {})
        self.namespaces[-2][u'en'] = [u'Media']
        self.namespaces[-1] = self.namespaces.get(-1, {})
        self.namespaces[-1][u'en'] = [u'Special']
        self.namespaces[1] = self.namespaces.get(1, {})
        self.namespaces[1][u'en'] = [u'Talk']
        self.namespaces[2] = self.namespaces.get(2, {})
        self.namespaces[2][u'en'] = [u'User']
        self.namespaces[3] = self.namespaces.get(3, {})
        self.namespaces[3][u'en'] = [u'User talk']
        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'en'] = [u'SotS2']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'en'] = [u'SotS2 talk']
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'en'] = [u'File']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'en'] = [u'File talk']
        self.namespaces[8] = self.namespaces.get(8, {})
        self.namespaces[8][u'en'] = [u'MediaWiki']
        self.namespaces[9] = self.namespaces.get(9, {})
        self.namespaces[9][u'en'] = [u'MediaWiki talk']
        self.namespaces[10] = self.namespaces.get(10, {})
        self.namespaces[10][u'en'] = [u'Template']
        self.namespaces[11] = self.namespaces.get(11, {})
        self.namespaces[11][u'en'] = [u'Template talk']
        self.namespaces[12] = self.namespaces.get(12, {})
        self.namespaces[12][u'en'] = [u'Help']
        self.namespaces[13] = self.namespaces.get(13, {})
        self.namespaces[13][u'en'] = [u'Help talk']
        self.namespaces[14] = self.namespaces.get(14, {})
        self.namespaces[14][u'en'] = [u'Category']
        self.namespaces[15] = self.namespaces.get(15, {})
        self.namespaces[15][u'en'] = [u'Category talk']

    def scriptpath(self, code):
        return {
            'en': u'',
        }[code]

    def version(self, code):
        return {
            'en': u'1.17.0',
        }[code]
